name: Django CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci:
    name: Continous Integration
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://jplautz:lingara@localhost:5432/db_fly

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: lingara
          POSTGRES_USER: jplautz
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432    
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.0
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.0'


    - name: Install Dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup .env
      run: cp .env.example .env
      
    - name: Run Tests
      run: python manage.py test

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      
    
    needs: ci

    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
